### ISSUE TITLE
Built-in abstractions in CF for ECS

### ISSUE THREAD

**Issue by bsideup** [awslabs/ecs-refarch-cloudformation#4]
Hi! 

Right now we have to copy-paste ECSLaunchConfiguration's magic from stack to stack. 

Having to call cf-init sounds like a non-native experience as well:
https://github.com/awslabs/ecs-refarch-cloudformation/blob/master/infrastructure/ecs-cluster.yaml#L107

I'm wondering if CF might provide some built-in abstractions for it? Currently it's looks almost like a hack :(

**Comment by PaulMaddox** [comment]
Hi Sergei,

You're correct - in this case [AWS::Cloudformation::Init](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html) is not doing much other than just setting the ECS_CLUSTER parameter, which could be done simply within the User Data script.

I think this is a force of habit of mine - I tend to use [AWS::Cloudformation::Init](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html) rather than UserData, as it allows you to signal success/failure of what is run back to the Auto Scaling Group with cfn-signal.

In this case - i'll leave it there as it's working, but if you're implementing this yourself it will probably just be easier to use the User Data directly.
